import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import AboutUs from "./PageSections/Homepage/AboutUs";
import Hero from "./PageSections/Homepage/Hero";
import OurServices from "./PageSections/Homepage/OurServices";
import Stats from "./PageSections/Homepage/Stats";
import Testimonial from "./PageSections/Homepage/Testimonial";
import WhatWeDo from "./PageSections/Homepage/WhatWeDo";
import WhyTrustUs from "./PageSections/Homepage/WhyTrustUs";

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="">
				<Hero />
				<AboutUs />
				<OurServices />
				<Stats />
				<WhyTrustUs />
				<Testimonial />
			</main>
		</>
	);
};

export default Home
